# fly.toml app configuration file generated for bennwallet on 2025-05-10T17:18:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bennwallet'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    YNAB_ACCOUNT_ID = ''
    YNAB_API_TOKEN = 'xIgepVnHjCxstZ30bAsr21TF40xORiT74fSD0GDWe9Y'
    YNAB_BUDGET_ID = '662ab203-7b47-45e1-8245-ce86ea9b848e'

[env]
  APP_ENV = 'development'
  ENVIRONMENT = 'development'
  NODE_ENV = 'development'
  PORT = '8080'
  RESET_DB = 'true'
  YNAB_ACCOUNT_ID = ''
  YNAB_API_TOKEN = 'xIgepVnHjCxstZ30bAsr21TF40xORiT74fSD0GDWe9Y'
  YNAB_BUDGET_ID = '662ab203-7b47-45e1-8245-ce86ea9b848e'

[[mounts]]
  source = 'bennwallet_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
